language: node_js
node_js:
  - '4'
  - '5'
  - '6'
before_script:
  - $(npm bin)/tsc --version
script:
  - npm run build
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
sudo: false
